name: "Osint_Stalker"
description: "A new Flutter project for osint stalker and looking leaked datas"
publish_to: 'none'

version: 3.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.0
  qr_flutter: ^4.1.0
  flutter_animate: ^4.5.0
  share_plus: ^10.1.4
  http: ^1.2.0
  package_info_plus: ^8.0.0
  local_auth: ^2.2.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true
  
  assets:
    - assets/icon/icon.png
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png" 
  min_sdk_android: 21