name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository code (Gunakan v4 terbaru)
    - uses: actions/checkout@v4

    # 2. Setup Java (Flutter terbaru butuh Java 17, bukan 12)
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    # 3. Setup Flutter Environment
    # HAPUS baris 'flutter-version' agar otomatis download yang TERBARU
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true # Fitur tambahan biar build berikutnya lebih cepat

    # 4. Get Dependencies
    - name: Get Dependencies
      run: flutter pub get

    # 5. Build APK (Release mode)
    # --split-per-abi dihapus agar jadi 1 file APK universal (fat apk)
    # Jika ingin file lebih kecil tapi terpisah, tambahkan --split-per-abi
    - name: Build APK
      run: flutter build apk --no-tree-shake-icons --release --obfuscate --split-debug-info=build/debug_info

    # 6. Upload Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk